### ISSUE TITLE
Remove mandatory args for system and env

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom-clients#3]
Doesn't require System and Environment args for newer versions of Stroom

**Comment by at055612** [comment]
Discussed with 10 and 66, they need to be removed as they are not required anymore, as you say.

May be worth adding a new optional multiple arg, ie. `--header` to take headers.  This would be in addition to the one that accepts a file of headers.  Would need precedence rules e.g. --header trumps the file based headers.

**Comment by at055612** [comment]
Fixed in #6
